### ISSUE TITLE
[Desktop - Services] - Overlap content above header

### ISSUE THREAD

**Issue by rmilano24** [rmilano24/impact3sixty#1]
Content area needs to overlap the header like the other pages.

![screen shot 2018-10-15 at 8 54 14 am](https://user-images.githubusercontent.com/1158973/46962405-ebb46380-d057-11e8-9c54-a397bc5f4a93.png)

**Comment by jonas-davidson** [comment]
Can't believe I missed that! I've adjusted the css to pull the content upward like the other pages (and the design).
![screen shot 2018-10-16 at 1 04 11 pm](https://user-images.githubusercontent.com/18017000/47044041-09f78d80-d144-11e8-8858-249e4b2cd734.png)
