### ISSUE TITLE
[Desktop - Home] Content gets tight on laptop 

### ISSUE THREAD

**Issue by rmilano24** [rmilano24/impact3sixty#2]
Anyway to move the logo up and/or make it smaller...possibly the "We believe..." text smaller for laptop height. Looks a bit cramped on my 13 inch.

![screen shot 2018-10-15 at 8 54 14 am](https://user-images.githubusercontent.com/1158973/46962550-4948b000-d058-11e8-8c4a-acdab63f8991.png)

**Comment by jonas-davidson** [comment]
I've made some adjustments to the padding and the logo's bottom margin based of screen height to make more space between the logo and content below. 

![screen shot 2018-10-16 at 12 49 59 pm](https://user-images.githubusercontent.com/18017000/47043277-124ec900-d142-11e8-84ea-0d04278688da.png)
