### ISSUE TITLE
[Desktop - Home] Slider Moving Footer

### ISSUE THREAD

**Issue by rmilano24** [rmilano24/impact3sixty#5]
Not the end of the world if this can't be fixed but throwing it out there in case you think of a possible solution while motavated.

**Comment by jonas-davidson** [comment]
@rmilano24 The alternative to this would be to have it not move the footer. But if we did that, longer quotes could potentially overlap the footer and we wouldn't have consistent whitespace between the footer and slider as the size of the quote container changed.
